public enum GamePacketType
{
    ENTER_GAME_WORLD = 1,
    CREATE_CHARACTER = 2,

    SET_ATTACK_TARGET = 12,

    USE_SKILL = 21,

    SPAWN_CHARACTER = 30,
    DESPAWN_CHARACTER = 31,
    EXECUTE_ATTACK_TARGET = 32,
    SET_DESTINATION = 33,
    DAMAGE_INFO = 34,
    SYNC_STAT = 35,
    SYNC_INVENTORY = 36,
    EXECUTE_SKILL_TARGET = 37,
    SET_POSITION = 38,
}